src/ISDemosSLN/IS.Web/Pages/Kubek/CreateNamespacePod.cshtml.cs
using Bogus;
using IS.Web.Interfaces;
using IS.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace IS.Web.Pages.Kubek;

public class CreateNamespacePodPageModel : PageModel
{
    private readonly IContainerRegistryService containerRegistryService;
    private readonly IKubernetesCrud kubernetesCrud;
    private readonly ILogger<CreateNamespacePodPageModel> logger;

    public CreateNamespacePodPageModel(IContainerRegistryService containerRegistryService,
        IKubernetesCrud kubernetesCrud,
        ILogger<CreateNamespacePodPageModel> logger)
    {
        this.containerRegistryService = containerRegistryService;
        this.kubernetesCrud = kubernetesCrud;
        this.logger = logger;
    }

    [BindProperty] public string NamespaceName { get; set; }
    [BindProperty] public string PodName { get; set; }
    [TempData] public string InfoText { get; set; }
    [BindProperty] public List<DockerImageViewModel> Images { get; set; }

    public void OnGet()
    {
        logger.LogInformation("Loading containers");
        var list = containerRegistryService.GetPredefinedImages();
        logger.LogInformation("Loaded list of {NumberOfImages} images", list.Count);
        Images = list;
    }

    public async Task<IActionResult> OnPostAsync()
    {
        if (string.IsNullOrEmpty(NamespaceName))
        {
            InfoText = "Enter name";
            return RedirectToPage("/Kubek/CreateNamespacePod");
        }

        if (!await kubernetesCrud.CreateNamespaceAsync(NamespaceName))
        {
            InfoText = "There has been an error with creating namespace in k8s, try again";
            return RedirectToPage("/Kubek/CreateNamespacePod");
        }

        var form = await Request.ReadFormAsync();
        var imageName = form["image"];
        
        logger.LogInformation("Received {ImageName}", imageName);
        if (!string.IsNullOrEmpty(imageName))
        {
            if (string.IsNullOrEmpty(PodName)) PodName = new Faker().Hacker.Abbreviation().ToLowerInvariant();

            if (!await kubernetesCrud.CreatePodAsync(NamespaceName, PodName, imageName))
            {
                InfoText = "There has been an error in creating pod, try again";
                return RedirectToPage("/Kubek/CreateNamespacePod");
            }
        }

        logger.LogInformation("Pod, namespace created!");
        return RedirectToPage("/Kubek/ListNamespaces");
    }
}

src/ISDemosSLN/IS.Web/Pages/Kubek/Dashboard.cshtml.cs
using IS.Web.Interfaces;
using IS.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace IS.Web.Pages.Kubek;

public class DashboardPageModel : PageModel
{
    private readonly ILogger<DashboardPageModel> logger;
    private readonly IKubernetesService kubernetesService;

    public DashboardPageModel(ILogger<DashboardPageModel> logger, IKubernetesService kubernetesService)
    {
        this.logger = logger;
        this.kubernetesService = kubernetesService;
    }

    public async Task OnGetAsync()
    {
        logger.LogInformation("Dashoard page loaded at {DateLoaded}, loading cluster information", DateTime.Now);
        BasicInformation = await kubernetesService.GetInfoAsync();
        logger.LogInformation("Loaded {KubernetesName} at {KubernetesAddress}", BasicInformation.Name,
            BasicInformation.Address);
    }

    [BindProperty] public KCInfo BasicInformation { get; set; }
}

src/ISDemosSLN/IS.Web/Pages/Kubek/ListNamespaces.cshtml.cs
using System.Diagnostics;
using IS.Web.Interfaces;
using IS.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace IS.Web.Pages.Kubek;

public class ListNamespacesPageModel : PageModel
{
    private readonly IKubernetesObjects kubernetesObjects;
    private readonly ILogger<ListNamespacesPageModel> logger;

    public ListNamespacesPageModel(IKubernetesObjects kubernetesObjects, 
        ILogger<ListNamespacesPageModel> logger)
    {
        this.kubernetesObjects = kubernetesObjects;
        this.logger = logger;
    }

    public async Task OnGetAsync()
    {
        logger.LogInformation("Getting data about namespaces");
        try
        {
            var namespaces = await kubernetesObjects.ListNamespacesAsync();
            foreach (var currentNamespace in namespaces)
            {
                string labels = string.Empty;
                if (currentNamespace.Metadata.Labels != null)
                {
                    foreach (var keyValuePair in currentNamespace.Metadata.Labels)
                    {
                        labels += $"{keyValuePair.Key}:{keyValuePair.Value} ";
                    }
                }

                NamespaceViewModels.Add(new NamespaceViewModel
                {
                    Id = currentNamespace.Metadata.Uid,
                    Name = currentNamespace.Metadata.Name,
                    CreationDate = currentNamespace.Metadata.CreationTimestamp ?? DateTime.Now,
                    Labels = labels
                });
            }
        }
        catch (Exception e)
        {
            Debug.Write(e.Message);
            logger.LogError(e.Message);
        }
        logger.LogInformation("Done loading namespaces");
    }

    [BindProperty(SupportsGet = true)] public string Name { get; set; }

    [BindProperty]
    public List<NamespaceViewModel> NamespaceViewModels { get; set; } = new();
}

src/ISDemosSLN/IS.Web/Pages/Kubek/PodForNamespace.cshtml.cs
using IS.Web.Interfaces;
using IS.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace IS.Web.Pages.Kubek;

public class PodForNamespacePageModel : PageModel
{
    private readonly IKubernetesObjects kubernetesObjects;

    public PodForNamespacePageModel(IKubernetesObjects kubernetesObjects) => 
        this.kubernetesObjects = kubernetesObjects;

    public async Task OnGetAsync(string name)
    {
        Name = name;
        var pods = await kubernetesObjects.ListPodsAsync(name);
        foreach (var pod in pods)
        {
            string labels = string.Empty;
            if (pod.Metadata.Labels != null)
            {
                foreach (var labelPair in pod.Metadata.Labels)
                {
                    labels += $" {labelPair.Key}:{labelPair.Value} ";
                }
            }

            PodViewModels.Add(new PodViewModel
            {
                Name = pod.Metadata.Name,
                Labels = labels
            });
        }
    }
        
    [BindProperty(SupportsGet = true)] public string Name { get; set; }
    [BindProperty]
    public List<PodViewModel> PodViewModels { get; set; } = new();
}

src/ISDemosSLN/IS.Web/Pages/Kubek/Store.cshtml.cs
using IS.Web.Helpers;
using IS.Web.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace IS.Web.Pages.Kubek;

public class StorePageModel : PageModel
{
    private readonly ILogger<StorePageModel> logger;
    private readonly IKubernetesCrud kubernetesCrud;

    public StorePageModel(ILogger<StorePageModel> logger, IKubernetesCrud kubernetesCrud)
    {
        this.logger = logger;
        this.kubernetesCrud = kubernetesCrud;
    }

    public void OnGet()
    {
        logger.LogInformation("Loaded scenario {DateLoaded}", DateTime.Now);
        if (TempData["StoreIP"] != null)
        {
            StoreIp = TempData["StoreIP"].ToString();
            logger.LogInformation("Loading assigned store IP {AssignedStoreIp}", StoreIp);
        }
    }

    public async Task<RedirectToPageResult> OnPostCreateScenarioAsync()
    {
        if (string.IsNullOrEmpty(NamespaceName))
        {
            InfoText = "Name is required!";
            return RedirectToPage("/Kubek/Store");
        }

        logger.LogInformation("Creating scenario at {DateCreated}", DateTime.Now);
        StoreIp = await kubernetesCrud.CreateScenarioAsync(NamespaceName);
        TempData["StoreIP"] = StoreIp;
        logger.LogInformation("Finished scenario, IP is {StoreIp}", StoreIp);

        return RedirectToPage("/Kubek/Store");
    }

    public async Task<RedirectToPageResult> OnPostDeleteScenarioAsync()
    {
        if (string.IsNullOrEmpty(NamespaceName))
        {
            InfoText = "Name is required!";
            return RedirectToPage("/Kubek/Store");
        }

        logger.LogInformation("Deleting scenario - the whole namespace {NamespaceName}", NamespaceName);
        await kubernetesCrud.DeleteScenarioAsync(NamespaceName);
        logger.LogInformation("Finish deleting scenario at {DateDeleted}", DateTime.Now);
        InfoText = "Scenario has been deleted, check namespaces";
        return RedirectToPage("/Kubek/ListNamespaces");
    }

    public async Task<IActionResult> OnPostAsync()
    {
        if (string.IsNullOrEmpty(StoreIp))
        {
            InfoText = "Store IP is required to create FQDN";
            return RedirectToPage("/Kubek/Store");
        }

        logger.LogInformation("Deleting scenario - the whole namespace {NamespaceName}", NamespaceName);
        var fqdn = await kubernetesCrud.AssignDnsAsync(DnsName, StoreIp, Constants.KubernetesRGName);
        logger.LogInformation("Finish allocating IP {StoreIP} to {FQDN}", StoreIp, fqdn);
        return Redirect($"http://{fqdn}");
    }

    [BindProperty] public string NamespaceName { get; set; }
    [BindProperty] public string StoreIp { get; set; }
    [BindProperty] public string DnsName { get; set; }
    [TempData] public string InfoText { get; set; }
}

src/ISDemosSLN/IS.Web/Pages/Kubek/CreateNamespacePod.cshtml
@page
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model CreateNamespacePodPageModel

@{
    ViewData["Title"] = "Create namespace and pod";
}

<h1>
    Create namespace and pod
</h1>

@if (!string.IsNullOrEmpty(Model.InfoText))
{
    <p class="text-danger font-weight-bolder mt-4 mb-4">@Model.InfoText</p>
}
<p>
    Use below form to create a pod from selected image in newly created namespace. It will automatically redirect you after creation
    to <a asp-page="/Kubek/ListNamespaces">List namespaces</a> option.
</p>

<form method="post">
    <div class="mb-3 row">
        <label class="col-sm-2 col-form-label"
               for="namespaceName">
            Namespace name
        </label>
        <div class="col-sm-10">
            <input asp-for="NamespaceName"
                   class="form-control"
                   id="namespaceName"
                   type="text">
            <small class="form-text text-muted"
                   id="namespaceNameInfo">
                Use all lowercase
            </small>
        </div>
    </div>
    <div class="mb-3 row">
        <label class="col-sm-2 col-form-label"
               for="podName">
            Pod name
        </label>
        <div class="col-sm-10">
            <input asp-for="PodName"
                   class="form-control"
                   id="podName"
                   type="text">
        </div>
    </div>
    <div class="mb-3 row">
        <label for="sizeCombo"
               class="col-sm-2 col-form-label">
            Select image to deploy to pod
        </label>
        <div class="col-sm-10">
            <select class="form-control"
                    id="sizeCombo"
                    name="image">
                @foreach (var listItem in Model.Images)
                {
                    <option value="@listItem.Name">@listItem.Name</option>
                }
            </select>
        </div>
    </div>
    <button class="btn btn-primary"
            type="submit">
        Create namespace and pod with selected image <i class="fa-solid fa-check"></i>
    </button>
</form>

src/ISDemosSLN/IS.Web/Pages/Kubek/Dashboard.cshtml
@page
@model DashboardPageModel

@{
    var clusterName = Model.BasicInformation.Name;
    ViewData["Title"] = "Kubek dashboard";
}

<h2>
    Kubek dashboard for <b>@clusterName</b>
</h2>

<p class="text-info">
    API master address:
    <a class="link-secondary"
       href="@Model.BasicInformation.Address">
        @Model.BasicInformation.Address
    </a>
</p>

<div class="row">
    <div class="col-md-4">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">List workloads</h5>
                <h6 class="card-subtitle mb-2 text-muted">list namespaces and workloads inside cluster @clusterName</h6>
                <p class="card-text">
                    List namespaces and workloads based on the user permission on the K8S cluster with their associated pods.
                </p>
                <a asp-page="/Kubek/ListNamespaces"
                   class="card-link">
                    Go <i class="fas fa-arrow-right"></i>
                </a>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Create namespaces and pod</h5>
                <h6 class="card-subtitle mb-2 text-muted">Create namespace in cluster @clusterName</h6>
                <p class="card-text">
                    Create a namespace and pod inside of cluster @clusterName with getting data from private container registry
                </p>
                <a asp-page="/Kubek/CreateNamespacePod"
                   class="card-link">
                    Go <i class="fas fa-arrow-right"></i>
                </a>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Scenario simulation</h5>
                <h6 class="card-subtitle mb-2 text-muted">Simulate web shop scenario</h6>
                <p class="card-text">
                    Simulate scenario of creating new store and getting IP to check the store is running.
                </p>
                <a asp-page="/Kubek/Store"
                   class="card-link">
                    Go <i class="fas fa-arrow-right"></i>
                </a>
            </div>
        </div>
    </div>
</div>

src/ISDemosSLN/IS.Web/Pages/Kubek/ListNamespaces.cshtml
@page
@model ListNamespacesPageModel

@{
    ViewData["Title"] = "List namespaces on cluster";
}

<h1>
    List namespaces
</h1>
<p>
    Below you can see all of the namespaces on the cluster (you can query the namespace to get back pods)
</p>

<table class="table table-light table-striped">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Creation date</th>
        <th scope="col">Labels</th>
        <th scope="col">...</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var currentModel in Model.NamespaceViewModels)
    {
        <tr>
            <td>@currentModel.Id</td>
            <td>@currentModel.Name</td>
            <td>@currentModel.CreationDate.ToShortDateString()</td>
            <td>@currentModel.Labels</td>
            <td>
                <a asp-page="/Kubek/PodForNamespace"
                   asp-route-name="@currentModel.Name">
                    Pods <i class="far fa-arrow-alt-circle-right"></i>
                </a>
            </td>
        </tr>
    }
    </tbody>
</table>

src/ISDemosSLN/IS.Web/Pages/Kubek/PodForNamespace.cshtml
@page "{name}"
@model PodForNamespacePageModel

@{
    ViewData["Title"] = "List pod for namespace " + Model.Name;
}

<div class="row">
    <div class="float-right">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a asp-page="/Kubek/Dashboard">Dashboard</a>
                </li>
                <li class="breadcrumb-item">
                    <a asp-page="/Kubek/ListNamespaces">Namespaces</a>
                </li>
                <li aria-current="page"
                    class="breadcrumb-item active">
                    Pods in namespace @Model.Name
                </li>
            </ol>
        </nav>
    </div>
</div>

<h1>List pod for namespace @Model.Name</h1>

<p class="text-info">All pods inside namespace</p>

<table class="table table-light table-striped">
    <thead>
    <tr>
        <th scope="col">Name</th>
        <th scope="col">Labels</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var currentModel in Model.PodViewModels)
    {
        <tr>
            <td>@currentModel.Name</td>
            <td>@currentModel.Labels</td>
        </tr>
    }
    </tbody>
</table>

src/ISDemosSLN/IS.Web/Pages/Kubek/Store.cshtml
@page
@model StorePageModel

@{
    ViewData["Title"] = "Store scenario";
}

<h1>
    Store scenario
</h1>
<p class="text-info">Below is an example of scenario, how you could use Kubernetes API's in action.</p>

@if (!string.IsNullOrEmpty(Model.InfoText))
{
    <p class="text-danger font-weight-bolder mt-4 mb-4">@Model.InfoText</p>
}
<h3>
    Create a new store
</h3>
<p>
    Use below details to create a new trial store to test out functionality and then, if you like it, you can
    buy the subscription.
</p>

@if (!string.IsNullOrEmpty(Model.StoreIp))
{
    <p class="text-success font-weight-bolder mt-4 mb-4">Navigate to <a href="http://@Model.StoreIp">the store</a>.</p>
    <form method="post">
        <input asp-for="StoreIp"
               type="hidden" />
        <div class="mb-3 row">
            <label class="col-sm-2 col-form-label"
                   for="dnsName">
                DNS name
            </label>
            <div class="col-sm-10">
                <input asp-for="DnsName"
                       class="form-control"
                       id="dnsName"
                       required="required"
                       type="text">
            </div>
        </div>
        <button class="btn btn-primary mr-3"
                type="submit">
            Create FQDN and redirect there <i class="fas fa-arrow-right"></i>
        </button>
    </form>
    <hr class="m-4"/>
}

<form method="post">
    <div class="mb-3 row">
        <label class="col-sm-2 col-form-label"
               for="namespaceName">
            Store name
        </label>
        <div class="col-sm-10">
            <input asp-for="NamespaceName"
                   class="form-control"
                   id="namespaceName"
                   type="text">
        </div>
    </div>
    <button asp-page-handler="CreateScenario"
            class="btn btn-primary mr-3"
            type="submit">
        Create scenario <i class="fas fa-store-alt"></i>
    </button>
    &nbsp;
    <button asp-page-handler="DeleteScenario"
            class="btn btn-danger"
            type="submit">
        Delete scenario <i class="fas fa-minus-circle"></i>
    </button>
</form>